[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = "rsproxy"

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

[source.sjtu]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[rustup.rsproxy]
dist-server = "https://rsproxy.cn"
update-root = "https://rsproxy.cn/rustup"

[rustup.ustc]
dist-server = "https://mirrors.ustc.edu.cn/rust-static"
update-root = "https://mirrors.ustc.edu.cn/rust-static/rustup"

[rustup.sjtu]
dist-server = "https://mirrors.sjtug.sjtu.edu.cn/rust-static"
update-root = "https://mirrors.sjtug.sjtu.edu.cn/rust-static/rustup"

[rustup.tuna]
dist-server = "https://mirrors.tuna.tsinghua.edu.cn/rustup"
update-root = "https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup"